FROM nvidia/cuda:8.0-devel-ubuntu16.04
LABEL MAINTAINER "Nicolas Hoferer"

RUN apt-get update
RUN apt-get update && apt-get install -y \
       curl \
       python3-numpy \
       python3-pip \
               && \
   apt-get clean && \
   rm -rf /var/lib/apt/lists/*
RUN apt-get update
RUN pip3 install --upgrade pip
RUN pip3 install tensorflow==1.2.1 keras==2.0.8

COPY /translation/ /translation
COPY /start_server.sh /

WORKDIR /
ENTRYPOINT ["sh"]
CMD ["./start_server.sh"]